model_name: RandomForestClassifier
params:
  n_estimators:
    - 50
    - 60
    - 70
    - 80
    - 90
    - 100
  min_samples_split:
    - 5
    - 3
    - 2
  random_state:
    - 0
    - 10
    - 42
  verbose:
    - 1
output_artifact_dir:
  models/
output_artifact_report_dir:
  reports/training/
figures:
  roc_curve:
    reports/figures/