model_name: XGBoostClassifier
params:
  eta:
    - 0.3
    - 0.25
    - 0.2
    - 0.15
  gamma:
    - 0
    - 0.001
    - 0.01
    - 0.1
  lambda:
    - 0.8
    - 0.9
    - 1.0
  alpha:
    - 0.8
    - 0.9
    - 1.0
output_artifact_dir:
  models/
output_artifact_report_dir:
  reports/training/