name: CI_test_pipeline1
on:
  pull_request:
    branches: '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      with:
        python-version: '3.9.5'
        architecture: 'x64'
      - name: Run test
        run: |
          python --version
          pwd
          pip install -r requirements.txt
          python -m src.tests.ci_check
